### ISSUE TITLE
synthv1 not starting in nsm

### ISSUE THREAD

**Issue by grammoboy2** [rncbc/synthv1#11]
Kudos for you nsm support!

synthv1 did not start though:

[non-session-manager] Sending add for: synthv1
[nsmd] Process has pid: 24569
[nsmd] Launching synthv1
[nsmd] Error starting process: No such file or directory
[nsmd] Client synthv1 died unexpectedly.
[non-session-manager] Sending resume
[nsmd] Process has pid: 24570
[nsmd] Launching synthv1
[nsmd] Error starting process: No such file or directory
[nsmd] Client synthv1 died unexpectedly

**Comment by grammoboy2** [comment]
Ok... take only the kudos. I started it with the wrong name.... (/me runs in shame ;) )

**Comment by falkTX** [comment]
This is why a pure line input in NSM is a bad idea! we have to remember the exact names to start the applications, wtf?

**Comment by grammoboy2** [comment]
On 30-01-2020 20:29, Filipe Coelho wrote:
>
> This is why a pure line input in NSM is a bad idea! we have to 
> remember the exact names to start the applications, wtf?
>
If this was the main problem, life would be easy. It has nsm support. I 
learned a lesson. Won't happen to me again in the next 50 years. Apps 
without nsm support is the problem.
>

**Comment by grammoboy2** [comment]
> On 30-01-2020 20:29, Filipe Coelho wrote:
>>
>> This is why a pure line input in NSM is a bad idea! we have to 
>> remember the exact names to start the applications, wtf?
>>
> If this was the main problem, life would be easy. It has nsm support. 
> I learned a lesson. Won't happen to me again in the next 50 years. 
> Apps without nsm support is the problem.
And why not just call the application synthv1?
>>

**Comment by falkTX** [comment]
It is not *the* problem, but it is *a* problem. I don't know how many times I have to repeat that... :(
