### ISSUE TITLE
A parameter to randomize synth parameter values

### ISSUE THREAD

**Issue by iurienistor** [rncbc/synthv1#12]
I propose a parameter that sets  the "randomize current parameter values". For example, I would set it to 20% or even more... find an interesting strange pad P, and than change the parameter to 1% and find something that works close to P.

Also, I propose to remove the warning popup since is not practical, and prevents quickly to make another random request.

**Comment by rncbc** [comment]
menu Help > Configure... > Options > Randomize factor.
