### ISSUE TITLE
Required and optional dependencies don't provide lv2/lv2plug.in/ns/extensions/ui/ui.h

### ISSUE THREAD

**Issue by yurivict** [rncbc/synthv1#13]
I have all required and optional dependencies installed but the file ```lv2/lv2plug.in/ns/extensions/ui/ui.h``` required by this line https://github.com/rncbc/synthv1/blob/master/CMakeLists.txt#L220 is still not found.

**Comment by rncbc** [comment]
cmake is not the official build system nor it is yet recommended

**Comment by AnClark** [comment]
> I have all required and optional dependencies installed but the file `lv2/lv2plug.in/ns/extensions/ui/ui.h` required by this line https://github.com/rncbc/synthv1/blob/master/CMakeLists.txt#L220 is still not found.

CMake works well for me (on Windows).

If you use Msys2 on Windows, you can consider [my PKGBUILD for LV2 SDK](https://github.com/AnClark/msys2-lv2-pkgbuild). 

Or if you use Linux distributions, consider following [LV2's official build guide](https://github.com/lv2/lv2#installation) (Arch Linux/Manjaro can install package `lv2` directly.)
