### ISSUE TITLE
A revers sample button

### ISSUE THREAD

**Issue by Reaper10** [rncbc/synthv1#3]
A revers sample button that can be automated and for live uses.

**Comment by rncbc** [comment]
On 09/13/2016 05:17 PM, Reaper10 wrote:

> A revers sample button that can be automated.

reverse of exactly what, may i ask?

## 

rncbc aka. Rui Nuno Capela

**Comment by Reaper10** [comment]
waxe files

**Comment by rncbc** [comment]
On 09/13/2016 05:35 PM, Reaper10 wrote:

> waxe files

synthv1 is NOT supposed to refer to any (sound) files

## what you mean?

rncbc aka. Rui Nuno Capela

**Comment by Reaper10** [comment]
oh whoops wrong plugin sorry
