### ISSUE TITLE
feature request: oscillators sync

### ISSUE THREAD

**Issue by chaocrator** [rncbc/synthv1#7]
please consider implementing oscillators sync feature (when osc 2 is reset on every cycle of osc 1).

**Comment by rncbc** [comment]
noted.

**Comment by rncbc** [comment]
please check https://github.com/rncbc/synthv1/commit/9ab991856ac4ac670550dad930628ae0cbf59b69 or better yet https://github.com/rncbc/synthv1/commit/0eaaeb6ae2e59020683c3e8793c00f07a1d57ccb .

**Comment by chaocrator** [comment]
cool.
will test it ASAP, maybe sunday.
(need to reanimate my arch installation first, because building on ubuntu scares me)

**Comment by chaocrator** [comment]
at last, managed to build & test.
it's working, and i'm absolutely satisfied. thank you.
i especially like that any oscillator in the pair can be either master or slave. 
nice work.
