### ISSUE TITLE
Proposal for QApplication instance

### ISSUE THREAD

**Issue by ghost** [rncbc/synthv1#9]
When the code checks for QApplication, also check the arguments in order to see of this instance comes from the host, and not has been created by other Qt plugins. If that plugin (X) that created the QApplication will delete the instance of QApplication when user closes the window for X plugin, all the rest Qt plugins windows opened will crash.

**Comment by rncbc** [comment]
possibly fixed on git head https://github.com/rncbc/synthv1/commit/0b314f6

cheers && thanks
